development:
  adapter: postgresql
  database: floatilla_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: floatilla_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: floatilla_production
  pool: 5
  timeout: 5000
